### ISSUE TITLE
Implement function to retrieve project push rules.

### ISSUE THREAD

**Issue by LRH539** [node-gitlab/node-gitlab#497]
**Description**
Right now, there's only an `updatePushRule()` function in `Projects.ts`, but there's no obvious way to retrieve the push rules, e.g. `getPushRules()`. I thought that this is probably contained if I retrieve a single projects properties via the API, but it doesn't contain any information about the push rules. 

**Proposal**
Implement a function, which queries this endpoint: ```GET /projects/:id/push_rule```.

**Comment by LRH539** [comment]
I realized there's a separate PushRules file, but on the GitLab API page it's listed under the projects API, so it's a bit confusing or is there in fact a dedicated PushRules endpoint?

**Comment by jdalrymple** [comment]
Yea It was just confusing to put under projects. Since most things are connected as a subresource of projects but are located in their own files. If I put pushrules there, i should put everything else there too. So to maintain consistency, I separated it out although the Gitlab API page doesn't really adhere to this (ie. Issues has its own page, though its a subresource of Projects).

The only exception to this, is if the subresource only has a couple endpoints.

**Comment by LRH539** [comment]
But in that case, should the updatePushRule() function not be removed as well and everything should be in the PushRules.ts in order to maintain consistency?

**Comment by jdalrymple** [comment]
Yea it should be removed. Probably existed before I added all the PushRules logic and I forgot to remove it from the Projects file. The only reason I would refrain from renaming it is because it gets...verbose. If only projects can have push rules, there is no point is adding the prefix. Unlike Milestones for example (which has ProjectMilestones,  GroupMilestones etc).

**Comment by LRH539** [comment]
I see, thanks for your quick response!

**Comment by jdalrymple** [comment]
No thank you! Always good to have another pair of eyes looking over things :D
